apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: t05qtf6jt-nodejs
  janus-idp.io/tekton: t05qtf6jt-nodejs
  backstage.io/kubernetes-id: t05qtf6jt-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: t05qtf6jt-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
